name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Nightly Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Install wasm-pack
      uses: jetli/wasm-pack-action@v0.3.0
    - name: Build (native code)
      run: cargo build
    - name: Build (WebAssembly)
      run: wasm-pack build --release --target no-modules
      working-directory: ./website
    # - name: Lint
    #   uses: actions-rs/clippy-check@v1
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     args: --all-features --no-deps -- --deny warnings
    - name: Test
      uses: actions-rs/tarpaulin@v0.1
    - name: Upload code coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Publish to GitHub Pages
      run: |
        git config --global user.name 'Annika L.'
        git config --global user.email 'annika0uwu@gmail.com'
        git add -f website/pkg
        git commit -m"Deploy to GitHub Pages"
        git push origin `git subtree split --prefix website main`:gh-pages --force
